package tictactoe.ui;

import tictactoe.ITicTacToe;
import tictactoe.Marker;
import tictactoe.board.Board;
import tictactoe.board.Cell;
import tictactoe.player.PlayerFactory;

import javax.swing.*;
import java.awt.*;
import java.io.PipedInputStream;
import java.io.PipedOutputStream;
import java.io.PrintWriter;
import java.util.List;
import java.util.Scanner;

import static tictactoe.TicTacToe.getNewBuilder;

public class SwingTicTacToe {
    //UI Code generated by Claude

    private ITicTacToe ticTacToe;
    private PrintWriter coordinateWriter;

    private JFrame frame;
    private JButton[][] cells;
    private JLabel statusLabel;

    private static final PlayerFactory playerFactory = new PlayerFactory();
    private static final int BOARD_SIZE = 3;

    public SwingTicTacToe() {
        showSetupDialog();
    }

    private void showSetupDialog() {
        Object[] options = {"vs Bot", "vs Human"};
        int choice = JOptionPane.showOptionDialog(null, "Choose your opponent:", "Tic Tac Toe",
                JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[0]);

        if (choice == JOptionPane.CLOSED_OPTION) System.exit(0);

        try {
            PipedOutputStream pipedOut = new PipedOutputStream();
            coordinateWriter = new PrintWriter(pipedOut, true);
            Scanner scanner = new Scanner(new PipedInputStream(pipedOut));

            ticTacToe = choice == 0
                    ? getNewBuilder(playerFactory).firstPlayerHuman(scanner).secondPlayerBot().boardSize(BOARD_SIZE).build()
                    : getNewBuilder(playerFactory).firstPlayerHuman(scanner).secondPlayerHuman(scanner).boardSize(BOARD_SIZE).build();
        } catch (Exception e) {
            throw new RuntimeException(e);
        }

        if (ticTacToe.player1IsHuman()) ticTacToe.enterPlayer1Name(promptName("Enter Player 1's name:"));
        if (ticTacToe.player2IsHuman()) ticTacToe.enterPlayer2Name(promptName("Enter Player 2's name:"));

        buildUI();
        playBotTurnIfNeeded();
    }

    private String promptName(String message) {
        String name = JOptionPane.showInputDialog(null, message, "Player Name", JOptionPane.PLAIN_MESSAGE);
        return (name == null || name.isBlank()) ? "Player" : name.trim();
    }

    private void buildUI() {
        frame = new JFrame("Tic Tac Toe");
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setLayout(new BorderLayout(8, 8));
        frame.getRootPane().setBorder(BorderFactory.createEmptyBorder(12, 12, 12, 12));

        statusLabel = new JLabel("Your turn!", SwingConstants.CENTER);
        statusLabel.setFont(new Font("SansSerif", Font.BOLD, 16));
        frame.add(statusLabel, BorderLayout.NORTH);

        JPanel boardPanel = new JPanel(new GridLayout(BOARD_SIZE, BOARD_SIZE, 6, 6));
        cells = new JButton[BOARD_SIZE][BOARD_SIZE];

        for (int row = 0; row < BOARD_SIZE; row++) {
            for (int col = 0; col < BOARD_SIZE; col++) {
                JButton cell = new JButton();
                cell.setFont(new Font("SansSerif", Font.BOLD, 40));
                cell.setFocusPainted(false);
                cell.setBackground(Color.WHITE);
                cell.setPreferredSize(new Dimension(100, 100));
                final int r = row, c = col;
                cell.addActionListener(e -> onCellClicked(r, c));
                cells[row][col] = cell;
                boardPanel.add(cell);
            }
        }

        frame.add(boardPanel, BorderLayout.CENTER);

        JButton restartButton = new JButton("Restart");
        restartButton.addActionListener(e -> restart());
        JPanel bottom = new JPanel();
        bottom.add(restartButton);
        frame.add(bottom, BorderLayout.SOUTH);

        frame.pack();
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
    }

    private void onCellClicked(int row, int col) {
        if (ticTacToe.isOver() || !ticTacToe.currentPlayerIsHuman()) {
            return;
        }
        setBoardEnabled(false);
        new SwingWorker<Void, Void>() {
            @Override protected Void doInBackground() {
                //adds int values to the buffer, so the scanner in human player picks it up
                coordinateWriter.println((row + 1) + " " + (col + 1));
                ticTacToe.playTurn();
                return null;
            }

            //after human player's turn has been processed, goes to bot's turn
            @Override protected void done() {
                refreshBoard();
                setBoardEnabled(true);
                if (!ticTacToe.isOver()) {
                    playBotTurnIfNeeded();
                }
            }
        }.execute();
    }

    private void playBotTurnIfNeeded() {
        if (ticTacToe.isOver() || ticTacToe.currentPlayerIsHuman()) { updateStatus(); return; }
        statusLabel.setText("Bot is thinking…");
        setBoardEnabled(false);
        new SwingWorker<Void, Void>() {
            @Override protected Void doInBackground() {
                try {
                    Thread.sleep(1000);
                } catch (InterruptedException e) {
                    Thread.currentThread().interrupt();
                }
                ticTacToe.playTurn();
                return null;
            }
            @Override protected void done() { refreshBoard(); setBoardEnabled(true); updateStatus(); }
        }.execute();
    }

    //prints board
    private void refreshBoard() {
        Board board = ticTacToe.getBoard();
        List<Cell[]> rows = board.getBoard();
        for (int row = 0; row < BOARD_SIZE; row++) {
            for (int col = 0; col < BOARD_SIZE; col++) {
                Marker marker = rows.get(row)[col].getMarker();
                JButton cell = cells[row][col];
                if (marker == null) {
                    cell.setText("");
                } else if (marker.toString().equals("X")) {
                    cell.setText("X"); cell.setForeground(new Color(0x1565C0));
                } else {
                    cell.setText("O"); cell.setForeground(new Color(0xC62828));
                }
            }
        }
        updateStatus();
    }

    private void updateStatus() {
        if (ticTacToe.isOver()) {
            String winner = ticTacToe.getWinningPlayersName();
            statusLabel.setText(winner == null ? "It's a draw!" : winner + " wins!");
            setBoardEnabled(false);
        } else {
            statusLabel.setText("Your turn!");
        }
    }

    //makes buttons clickable or not
    private void setBoardEnabled(boolean enabled) {
        for (JButton[] row : cells)
            for (JButton cell : row)
                cell.setEnabled(enabled);
    }

    private void restart() { frame.dispose(); showSetupDialog(); }

    public static void main(String[] args) { SwingUtilities.invokeLater(SwingTicTacToe::new); }
}