package tictactoe.ui;

import tictactoe.ITicTacToe;
import tictactoe.Marker;
import tictactoe.TicTacToe;
import tictactoe.board.Board;
import tictactoe.board.Cell;
import tictactoe.player.PlayerFactory;

import javax.swing.*;
import java.awt.*;

import static tictactoe.TicTacToe.getNewBuilder;

public class SwingTicTacToe {
    //UI Code generated by Claude

    private ITicTacToe ticTacToe;

    private JFrame frame;
    private JButton[][] cells;
    private JLabel statusLabel;

    private static final PlayerFactory playerFactory = new PlayerFactory();
    private static final int BOARD_SIZE = 3;

    public SwingTicTacToe() {
        showSetupDialog();
    }

    private void showSetupDialog() {
        Object[] options = {"vs Bot", "vs Human"};
        int choice = JOptionPane.showOptionDialog(null, "Choose your opponent:", "Tic Tac Toe",
                JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[0]);

        if (choice == JOptionPane.CLOSED_OPTION) System.exit(0);

        Object[] winOptions = {"Standard", "Vertical", "Diagonal", "Horizontal"};
        int winChoice = JOptionPane.showOptionDialog(null, "Choose your win strategy:", "Tic Tac Toe",
                JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, winOptions, winOptions[0]);

        if (winChoice == JOptionPane.CLOSED_OPTION) System.exit(0);

        try {
            TicTacToe.Builder builder = getNewBuilder(playerFactory).firstPlayerHuman().boardSize(3);


            if (choice == 0) {
                builder = builder.secondPlayerBot();
            } else {
                builder = builder.secondPlayerHuman();
            }

            if (winChoice == 0) {
                builder = builder.standardWin();
            } else if (winChoice == 1) {
                builder = builder.verticalWin();
            } else if (winChoice == 2) {
                builder = builder.diagonalWin();
            } else if (winChoice == 3) {
                builder = builder.horizontalWin();
            }

            ticTacToe = builder.build();

        } catch (Exception e) {
            throw new RuntimeException(e);
        }

        if (ticTacToe.player1IsHuman()) ticTacToe.enterPlayer1Name(promptName("Enter Player 1's name:"));
        if (ticTacToe.player2IsHuman()) ticTacToe.enterPlayer2Name(promptName("Enter Player 2's name:"));

        buildUI();
        playBotTurnIfNeeded();
    }

    private String promptName(String message) {
        String name = JOptionPane.showInputDialog(null, message, "Player Name", JOptionPane.PLAIN_MESSAGE);
        return (name == null || name.isBlank()) ? "Player" : name.trim();
    }

    private void buildUI() {
        frame = new JFrame("Tic Tac Toe");
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setLayout(new BorderLayout(8, 8));
        frame.getRootPane().setBorder(BorderFactory.createEmptyBorder(12, 12, 12, 12));

        statusLabel = new JLabel("Your turn!", SwingConstants.CENTER);
        statusLabel.setFont(new Font("SansSerif", Font.BOLD, 16));
        frame.add(statusLabel, BorderLayout.NORTH);

        JPanel boardPanel = new JPanel(new GridLayout(BOARD_SIZE, BOARD_SIZE, 6, 6));
        cells = new JButton[BOARD_SIZE][BOARD_SIZE];

        for (int row = 0; row < BOARD_SIZE; row++) {
            for (int col = 0; col < BOARD_SIZE; col++) {
                JButton cell = new JButton();
                cell.setFont(new Font("SansSerif", Font.BOLD, 40));
                cell.setFocusPainted(false);
                cell.setBackground(Color.WHITE);
                cell.setPreferredSize(new Dimension(100, 100));
                final int r = row, c = col;
                cell.addActionListener(e -> onCellClicked(r, c));
                cells[row][col] = cell;
                boardPanel.add(cell);
            }
        }

        frame.add(boardPanel, BorderLayout.CENTER);

        JButton restartButton = new JButton("Restart");
        restartButton.setFocusable(false);
        restartButton.addActionListener(e -> restart());

        JButton undoButton = new JButton("Undo");
        undoButton.setFocusable(false);
        undoButton.addActionListener(e -> onUndo());

        JPanel bottom = new JPanel();
        bottom.add(undoButton);
        bottom.add(restartButton);
        frame.add(bottom, BorderLayout.SOUTH);
        frame.pack();
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
    }

    private void onCellClicked(int row, int col) {
        if (ticTacToe.isOver() || !ticTacToe.currentPlayerIsHuman()) {
            return;
        }
        setBoardEnabled(false);
        new SwingWorker<Void, Void>() {
            @Override protected Void doInBackground() {
                ticTacToe.pickMove(row + 1, col + 1);
                return null;
            }

            //after human player's turn has been processed, goes to bot's turn
            @Override protected void done() {
                refreshBoard();
                setBoardEnabled(true);
                if (!ticTacToe.isOver()) {
                    playBotTurnIfNeeded();
                }
            }
        }.execute();
    }

    private void playBotTurnIfNeeded() {
        if (ticTacToe.isOver() || ticTacToe.currentPlayerIsHuman()) { updateStatus(); return; }
        statusLabel.setText("Bot is thinking…");
        setBoardEnabled(false);
        new SwingWorker<Void, Void>() {
            @Override protected Void doInBackground() {
                try {
                    Thread.sleep(1000);
                } catch (InterruptedException e) {
                    Thread.currentThread().interrupt();
                }
                ticTacToe.pickMove();
                return null;
            }
            @Override protected void done() { refreshBoard(); setBoardEnabled(true); updateStatus(); }
        }.execute();
    }

    //prints board
    private void refreshBoard() {
        Board board = ticTacToe.getBoard();
        Cell[][] rows = board.getBoard();
        for (int row = 0; row < BOARD_SIZE; row++) {
            for (int col = 0; col < BOARD_SIZE; col++) {
                Marker marker = rows[row][col].getMarker();
                JButton cell = cells[row][col];
                if (marker == null) {
                    cell.setText("");
                } else if (marker.toString().equals("X")) {
                    cell.setText("X"); cell.setForeground(new Color(0x1565C0));
                } else {
                    cell.setText("O"); cell.setForeground(new Color(0xC62828));
                }
            }
        }
        updateStatus();
    }

    private void updateStatus() {
        if (ticTacToe.isOver()) {
            if (ticTacToe.getWinningPlayer() != null) {
                String winner = ticTacToe.getWinningPlayersName();
                statusLabel.setText(winner + " wins!");
            }
            else {
                statusLabel.setText("It's a draw!");
            }
            setBoardEnabled(false);
        } else {
            statusLabel.setText("Your turn!");
        }
    }

    //makes buttons clickable or not
    private void setBoardEnabled(boolean enabled) {
        for (JButton[] row : cells)
            for (JButton cell : row)
                cell.setEnabled(enabled);
    }

    private void onUndo() {
        if (!ticTacToe.canUndo()) return;
        setBoardEnabled(false);
        new SwingWorker<Void, Void>() {
            @Override protected Void doInBackground() {
                ticTacToe.undoMove();
                return null;
            }
            @Override protected void done() {
                refreshBoard();
                setBoardEnabled(true);
                updateStatus();
            }
        }.execute();
    }

    private void restart() { frame.dispose(); showSetupDialog(); }

    public static void main(String[] args) { SwingUtilities.invokeLater(SwingTicTacToe::new); }
}